version: 2

defaults: &defaults
  working_directory: ~/app
  docker:
    - image: node:8.9.2-alpine
  environment:
    YARN_CACHE_FOLDER: "/home/circleci/.yarn-cache"

jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
            - npm-deps-{{ checksum "yarn.lock" }}
      - run: yarn install
      - save_cache:
          key: npm-deps-{{ checksum "yarn.lock" }}
          paths:
            - node_modules
      - persist_to_workspace:
          root: /home/circleci/
          paths:
            - app
  test:
    <<: *defaults
    steps:
      - attach_workspace:
          at: /home/circleci/
      - run: yarn add codecov
      - run: yarn test && npx codecov


workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build