version: 2
jobs:
  build:
    docker:
      - image: node:8.9.2-alpine

    working_directory: ~/repo

    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      # run tests!
      - run: yarn test
  test:
    steps:
      post:
        - bash <(curl -s https://codecov.io/bash)
