version: 2

defaults: &defaults
  working_directory: ~/app
  docker:
    - image: node:8.9.2-alpine

jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
            - npm-deps-{{ checksum "yarn.lock" }}
      - run: yarn install
      - save_cache:
          key: npm-deps-{{ checksum "yarn.lock" }}
          paths:
            - node_modules
  test:
    <<: *defaults
    steps:
      - run: yarn add codecov
      - run: yarn test && npx codecov


workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build