version: 2

defaults: &defaults
  working_directory: ~/app
  docker:
    - image: node:8.9.2-alpine

jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      # run tests!
      - run: yarn test
  test:
    <<: *defaults
    steps:
      - post:
        - bash <(curl -s https://codecov.io/bash)


workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build